import type { SavedProject, ProjectDetail } from "../../../shared/types";

export function exportToMarkdown(project: SavedProject | ProjectDetail): string {
  const isSaved = "createdAt" in project;
  const tags = (project.tags || []).map(t => `\`${t}\``).join(" ");
  
  const content = `# ${project.title}

> **${project.pitch}**

**Category:** ${project.category || "AI Systems"} | **Difficulty:** ${project.difficulty} | **Time Estimate:** ${project.timeEstimate} | **Goal:** ${project.researchLevel || "Research"}

---

## 📊 Scores
- **Originality:** ${project.originalityScore}/100
- **Recruiter:** ${project.recruiterScore}/100
- **Startup:** ${project.startupScore}/100
- **Publishability:** ${project.publishabilityScore || 80}/100

${project.researchBottleneck ? `> ⚠️ **Research Bottleneck:** ${project.researchBottleneck}` : ""}

---

## 🔬 Deep Dive

### Problem Statement
${project.problemStatement || "N/A"}

### Core Innovation
${project.coreInnovation || "N/A"}

### Architecture
\`\`\`
${project.architecture || "N/A"}
\`\`\`

### Technical Stack & Skills
- **Skills:** ${(project.requiredSkills || []).join(", ")}
- **Stack:** ${(project.techStack || []).join(", ")}
- **Models:** ${(project.recommendedModels || []).join(", ")}
- **Datasets:** ${(project.datasets || []).join(", ")}

### Evaluation Metrics
${(project.evaluationMetrics || []).map(m => `- ${m}`).join("\n")}

### Deployment & Scaling
**Deployment:** ${project.deployment || "N/A"}
${(project.scalingIdeas || []).length > 0 ? `\n**Scaling Ideas:**\n${project.scalingIdeas.map(i => `- ${i}`).join("\n")}` : ""}

### Future Improvements
${(project.futureImprovements || []).map(i => `- ${i}`).join("\n")}

---

## 📅 Build Plan (Roadmap)

${(project.roadmap || []).map((step, i) => `### Week ${i + 1}\n- [ ] ${step}`).join("\n\n")}

---
*Generated by Frontier on ${isSaved ? new Date(project.createdAt).toLocaleDateString() : new Date().toLocaleDateString()}.*
`;

  return content;
}

export function downloadMarkdown(project: SavedProject | ProjectDetail) {
  const md = exportToMarkdown(project);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${project.id || "project"}-blueprint.md`;
  a.click();
  URL.revokeObjectURL(url);
}
